### ISSUE TITLE
Transform output is inconsistent with developer experience.

### ISSUE THREAD

**Issue by trusktr** [d3/d3-zoom#108]
Continuing from https://github.com/d3/d3/issues/3119#issuecomment-314589750

> Instead, transforms are represented as a matrix, and transform operations derive a new matrix. So, the two operations you describe result in identical transforms which are formatted identically by transform.toString:

I understand.

This is more of a feature request: a feature to preserve meaningful transform input.

This could be useful in cases where we wish to retrieve the original values that were inputted.

In other libraries (f.e. Three.js, Pixi.js, etc), one can set `position.x`, `position.y`, etc, and later can retrieve those original values.

**Comment by mbostock** [comment]
Sorry, but this is not a feature request I’m willing to support. You might be able to use [d3-transform](https://github.com/trinary/d3-transform). If it helps, I would be willing to consider changing *zoom*.transform so that you can pass in an object with *x*, *y* and *k* properties rather than requiring an instance of d3.zoomTransform; that could possibly let you use d3-transform (or another class of your own design) with the *zoom*.transform API.
