### ISSUE TITLE
Having difficulties using d3-zoom with d3 v4.0

### ISSUE THREAD

**Issue by holyxiaoxin** [d3/d3-zoom#27]
I am using webpack and trying add zoom to an svg with the following code:

```js
import d3 from 'd3';
import d3Zoom from 'd3-zoom';
Object.assign(d3, { zoom: d3Zoom.zoom, zoomTransform: d3Zoom.zoomTransform });

d3.select('svg').call(d3.zoom().on("zoom", ()=> {
   console.log('zooming')
}));
```

But I am getting this error:

`Uncaught TypeError: Cannot read property 'button' of null.`

from:

``` js
// d3-zoom/build/d3-zoom.js, v:`0.1.0`
function defaultFilter() {
   return !d3Selection.event.button;
}
```

Are there any examples to integrate zoom with existing d3 graphs? I am trying to do pan and zoom. Thanks.

**Comment by mbostock** [comment]
I don’t think you can import d3-zoom that way using Webpack; you’re mixing the default build of D3 (assuming you ran `npm install d3@next` and that your `d3` refers to D3 4.0) with an individual module, d3-zoom. So when d3-zoom looks for the d3-selection module, it’s undefined. Maybe it would work if you required the [D3 modules](https://github.com/d3) individually, instead?

Unfortunately, I don’t use Webpack, so I can’t help you use Webpack. I’m just guessing…

Here are a few ways to use d3-zoom:

One. You can use the latest alpha build of [D3 4.0](https://github.com/d3/d3), alpha 41, which now includes d3-zoom. You can install D3 4.0 using `npm install d3@next` or you can download it from [d3js.org](https://d3js.org/d3.v4.0.0-alpha.41.min.js) or [npmcdn.com](https://npmcdn.com/d3@next?main=browser).

Two. You can load the D3 modules individually using vanilla script tags or RequireJS. This is described in the [README](https://github.com/d3/d3-zoom/blob/master/README.md):

```html
<script src="https://d3js.org/d3-color.v0.4.min.js"></script>
<script src="https://d3js.org/d3-dispatch.v0.4.min.js"></script>
<script src="https://d3js.org/d3-ease.v0.7.min.js"></script>
<script src="https://d3js.org/d3-interpolate.v0.8.min.js"></script>
<script src="https://d3js.org/d3-selection.v0.7.min.js"></script>
<script src="https://d3js.org/d3-timer.v0.4.min.js"></script>
<script src="https://d3js.org/d3-transition.v0.2.min.js"></script>
<script src="https://d3js.org/d3-drag.v0.2.min.js"></script>
<script src="https://d3js.org/d3-zoom.v0.1.min.js"></script>
```

Three. You can simply concatenate the above files together into a single bundle using [`cat`](https://en.wikipedia.org/wiki/Cat_\(Unix\)). In this case, as with the second approach, the modules are exposed as `d3_color`, `d3_dispatch` and the like, rather than a single `d3` object. But this works as a poor man’s bundler.

Four. You can use [Rollup](http://rollupjs.org) to produce a custom bundle, importing just the symbols you need, and defining your own custom `d3` object which you can then import into Webpack. Here are two examples:

http://bl.ocks.org/mbostock/bb09af4c39c79cffcde4
http://bl.ocks.org/mbostock/97557a39b4bfc8229786c8bccb54074d
