### ISSUE TITLE
Slowdown due to many zoom events per frame

### ISSUE THREAD

**Issue by nponeccop** [d3/d3-zoom#30]
A simple benchmark shows that mouse events happen more often than screen refreshes. I.e. `zoom()` handler is called 3 to 120 times more frequently than `requestAnimationFrame()` handler on different hardware. So heavy work (DOM and other painting) should be avoided in `.zoom()` handlers and performed in `requestAnimationFrame` instead (or using a 16ms timer as a poor man substitute if `rAF` is not available but the browser is otherwise capable enough).

What do you think? Can such workflow be supported by library code? Does it have direct support in D3 now?

In multiplayer games and other realtime interactions where latency is important it is nice to get all raw input early, to feed into predictive models and/or send to game server. But in simple animations and visualization controls it is seldom necessary. So one approach for D3 could be to modify zoom events so they are fired only once per frame. E.g.

```
function onDomMouseMove() { lastCoords = event.transform; zoomHappened = true }
function onAnimationFrame() { if (zoomHappened) fireAllZoomHandlers(lastCoords) }
```

I modified heavily your gradient panning gist to demonstrate the advantages:

https://github.com/streamcode9/svg-time-series/tree/626ddf9bed104bb457217f2183084b91a4b4261f/benchmarks/d3-myaxis

The code is rather dirty proof-of-concept, and I also fixed extra attribute modifications in axis by copy-pasting axis module in my code. But even zoom event filtering alone [index.js#L252-293](https://github.com/streamcode9/svg-time-series/blob/626ddf9bed104bb457217f2183084b91a4b4261f/benchmarks/d3-myaxis/index.js#L252-293) shows improvement in FPS on slow devices.

My tests show that in panning `lastCoords` approach works better than `firstCoords`, as the observed distance between mouse pointer and object being dragged is smaller.

**Comment by mbostock** [comment]
It wouldn’t be possible to defer the zoom event until a subsequent animation frame; the zoom event needs to happen during the native input event that triggered it, setting *event*.sourceEvent and allowing the source event to be affected, such as stopping propagation or preventing default behaviors.

You could perhaps throttle the input events though, so that only some mousemove events (for example) trigger a corresponding zoom event. But my guess is this could make the zoom behavior laggy. It’s probably better to handle the input events as they are triggered, and then defer the redraw to an animation frame as you suggest. You can use d3.timeout to make this a little bit easier than using requestAnimationFrame yourself.

**Comment by nponeccop** [comment]
I implemented the redraw to an animation frame approach in your gradient pan-zoom example:

http://bl.ocks.org/nponeccop/e3a9203036dd68b3a1f9433e8200a647

What do you think? Can it be done better? Do we need some kind of tutorial on how to avoid redraws?

**Comment by mbostock** [comment]
Closing to inactivity, plus you can throttle work in your zoom event listeners rather than relying on the zoom behavior to throttle for you.
