### ISSUE TITLE
emulate double click with double touch/tap events and link their handlers

### ISSUE THREAD

**Issue by virgile-hogman** [d3/d3-zoom#31]
Hi, i'm trying to define a zoom behavior mostly for panning, where a double click on the background would unzoom and return at scale 1 instead of zooming (i use zoom scales on other objects than the background). This works very fine with the desktop version through  `.on("dblclick.zoom")` handler.
```
 mysvg.selectAll("image.bg")
    .call(zoom)
    .on("dblclick.zoom", autoRescale)
```
Good so far!

However i have an issue i can't solve on mobile with the **touch** events. I would like to emulate the same doubleclick behavior when the user makes a **double tap**.

If i add a handler `.on("touchstart.zoom", myhandler)` i manage to emulate the double tap correctly (through my own timer). But then i lose all the gestures handled by d3 such as standard panning and pinch zoom and i'd definitely want to keep those.

I went a bit in the code and noticed the `touchstart()` inner function calls `dblclicked()` inner function regardless of my own handler that will be ignored. Maybe there could be a solution here?

I haven't found any workaround. I tried the dirty way reading the internal `touchstart.zoom` callback function and calling it again but it has side effects. I also tried capturing the dispatch events such as `zoomstart` but i couldn't solve this. Any suggestion?

Also i'm a bit lost with the documentation, between these 2 pages:
- Zoom main API ref: https://github.com/d3/d3/wiki/Zoom-Behavior
- Zoom package: https://github.com/d3/d3-zoom

What is the good API reference? For instance the events are called `zoomstart, zoom, zoomend` in the main page but `start, zoom, end` in the zoom package (without prefix). The `filter` function described in the package does not seem to be available on the zoom behavior but maybe i missed something here. The documentation in the zoom package is more detailed but the API reference matches the version i'm using (d3.min 3.5.16). A bit confused where to go here.

Many thanks for this awesome library!

**Comment by mbostock** [comment]
This is the D3 3.x API Reference: https://github.com/d3/d3/wiki/Zoom-Behavior It will be moved when D3 4.0 is officially released; currently it’s still alpha.

This is the D3 4.0 API Reference (and the API Reference for this module, d3-zoom): https://github.com/d3/d3-zoom

One reason I’m moving the API Reference from the wiki to the git module is to keep the documentation in sync with the releases, and to preserve documentation for old releases. But I can’t do that retroactively for D3 3.x.
 
If you want to initiate a zoom transition, you’ll want to call [*zoom*.transform](https://github.com/d3/d3-zoom#zoom_transform) from a transition (or from a selection, if you want the change to be instantaneous. This is demonstrated in the linked [Zoom Transitions example](http://bl.ocks.org/mbostock/b783fbb2e673561d214e09c7fb5cedee).

To detect a double tap, you’ll want to register your own touchstart listener, but you shouldn’t use the same name (“.zoom”) as the one the zoom behavior uses, because then your touchstart listener will replace the zoom behavior’s (or vice versa, depending on order) and you’ll prevent all touch-based zooming. I recommend registering your touchstart listener before applying the zoom behavior to the selection, and then using *event*.stopImmediatePropagation when you detect a doubletap to prevent the zoom behavior from receiving this touchstart event.

There’s not currently a hook in the zoom behavior to override what happens on double tap: it invokes the internal dblclicked listener directly to initiate a zoom-in. I suppose we could make the customizable, but in general, I prefer customizing behavior outside the zoom behavior by capturing input events before the zoom behavior receives them, as described in the previous paragraph.

**Comment by virgile-hogman** [comment]
Awesome, it works like a charm! Many thanks! :)

Your solution consisting to register my callback with another name makes perfectly sense. I didn't know about `event.stopImmediatePropagation()` to solve the conflicts in the event chain. This should work as long as my callback is executed before the one in zoom which should be the case if the callbacks follow the same order they have been registered.

Just to try, i registered my callback after `call(zoom)` and surprisingly it worked the same. The order is preserved so in theory there should be some conflicts as the zoom events are triggered before. But they were not visible here, as if they became cancelled. Anyway it was just a test to understand better. To stop the propagation before is preferable and the issue is solved :)
