### ISSUE TITLE
Behaviour changed?

### ISSUE THREAD

**Issue by isaomatsunami** [d3/d3-zoom#43]
This is not a request.
When zoom is constrained by translateExtent(), dragging out of the extent may cause scale-up to keep to conform to translateExtent.
For example, try drag the cross section chart of a railroad route.( http://www.chunichi.co.jp/ee/feature/chuo/ ).

This is just a little enquiry. That the dragging near the extent border should not trigger scaling-up is a design ?

**Comment by mbostock** [comment]
That page appears to be using D3 3.x (from what I can tell from the resources tab) and *zoom*.translateExtent is a new feature in D3 4.0. I’m not sure I entirely understand what you are asking, but no, *zoom*.translateExtent doesn’t affect the scale when you attempt to translate outside of the viewable area: it simply constraints panning. However, when you zoom out, the translate extent may also cause panning so as to again constrain the viewport to the viewable area.

If you want different behavior, you can listen to *zoom* events and modify the zoom transform rather than relying on *zoom*.translateExtent.

**Comment by isaomatsunami** [comment]
Thank you very much.
I am loyal to the design, won't change this basic behavior.

It's only 5 years ago I spent a whole NERVE-BREAKING day to check THAT interpolating function dealing with clickPoint/window/viewport in ActionScript. I won't/can't repeat it now.
