### ISSUE TITLE
How to reset zoom?

### ISSUE THREAD

**Issue by adonespitogo** [d3/d3-zoom#44]
Here's my reset function:
```
function reset() {
  var t = d3.zoomIdentity.translate(0,0).scale(1)
  chart_svg.call(zoomListener.transform, t)
}
```
But the resulting transform property applied to my chart is `translate (-xxxxx,-xxx) scale (1)`.

**Comment by mbostock** [comment]
That looks approximately correct, although the `t` you have defined is equivalent to d3.zoomIdentity, so you can more simply say:

```js
selection.call(zoom.transform, d3.zoomIdentity);
```

As for why you are seeing a translate applied, I have no idea based on the snippet you posted. (What is `zoomListener`, for instance?) The only way I can investigate this issue is if you post a link to a running example, ideally on bl.ocks.org, that demonstrates the problem.

**Comment by adonespitogo** [comment]
Hello, thanks for the quick response. Here is the running sample I have http://run.plnkr.co/plunks/hjiMeumJzL10TmWKkijV/

**Comment by mbostock** [comment]
The problem is your code here:

```js
if (!d3.event.transform.x) d3.event.transform.x = prev_zoom_x;
else prev_zoom_x = d3.event.transform.x;
if (!d3.event.transform.y) d3.event.transform.y = prev_zoom_y;
else prev_zoom_y = d3.event.transform.y;
```

I’m not sure why you are doing this, but when you reset to the identity transform, *transform*.x and *transform*.y will be zero, so you’ll use `prev_zoom_x` and `prev_zoom_y` rather than [0,0].

**Comment by mbostock** [comment]
Please use Stack Overflow tag d3.js or the d3-js Google group to ask for further help debugging your code. If you are able to isolate an issue with D3 then I will investigate further, but I often don’t have time to debug general usage of D3. Thanks for your understanding.

**Comment by adonespitogo** [comment]
Thanks a lot man.

**Comment by Thebee23** [comment]
does any one have reset function for d3 v2 zoom?
