### ISSUE TITLE
d3.zoomTransform(node)

### ISSUE THREAD

**Issue by yourinoelnelson** [d3/d3-zoom#47]
I can't seem to figure out how to use this function, everything I have tried has returned the identity matrix and never the current transform that is being applied.

```
var zoom = d3.zoom()
             .scaleExtent([0.3,2])
             .on("zoom", zoomed);


var svg = d3.select("body")
            .append("svg")
              .attr("width", viewerWidth)
              .attr("height", viewerHeight)
            .call(zoom)
            .append("g");

function zoomed() {
  var t = d3.event.transform;
  svg.attr("transform", "translate(" + t.x + "," + t.y + ") scale(" + t.k + ")");
}
```

If i zoom or pane on the page and then `typed3.zoomTransform(svg)` all i get back is the identity matrix, I tried `d3.zoomTransform(zoom)` and `d3.zoomTransform(zoom,svg)` and all of them give me the same identity matrix...
If I look at svg in the console the __zoom  parameter is not there.
Any suggestions on this? Thank you

**Comment by mbostock** [comment]
d3.zoomTransform takes a node, not a selection. You must pass it a node that you previously applied the zoom behavior to. Your snippet is somewhat confusing because the `svg` selection does not refer to the SVG element but to the child G element.

If you want to access the transform within a zoom event listener, it is `d3.event.transform` (or equivalently `d3.zoomTransform(this)`).

Outside of an event listener, it would be `d3.zoomTransform(d3.select("svg").node())` or some equivalent method of selecting the SVG element you previously applied the zoom behavior to.
