### ISSUE TITLE
Handle translateExtent smaller than view extent?

### ISSUE THREAD

**Issue by Servuc** [d3/d3-zoom#50]
Hi,

I think I have find a bug.

When `d3.zoom.translateExtent` is set with value `[ [0,0], [ svgWidth, svgHeight ] ]`, the SVG madly move after some zoom/unzoom. 

You can try it here : http://blockbuilder.org/Servuc/be15ded279a85c034d092589b3d13724

Comment/Uncomment line 1745 to see with and withtout `translateExtent`.

Have a good coding day :) 

Servuc.
(D3 is very cool !!!)

**Comment by mbostock** [comment]
The problem is that the translateExtent you’ve specified, `[[0, 0], [839, 2139]]`, is smaller than the zoom extent, `[[0, 0], [944, 484]]`. So there’s no way to satisfy the requested constraint. If you increase the translateExtent to `[[0, 0], [944, 2139]]` it should be fine.

I’ll leave this bug open as a note that the zoom behavior could handle this edge case better, probably by locking the translation on the over-constrained access to the midpoint of both extents.
