### ISSUE TITLE
add ability to change interpolateZoom function

### ISSUE THREAD

**Issue by unstoppablecarl** [d3/d3-zoom#54]
There is currently no way to change the current `interpolateZoom` function. I would like to be able to have a simple direct pan / zoom tween transition.

**Comment by mbostock** [comment]
Sounds reasonable. I’m added [*zoom*.interpolate](https://github.com/d3/d3-zoom#zoom_interpolate). If you set it to [d3.interpolate](https://github.com/d3/d3-interpolate#interpolate) instead of the default [d3.interpolateZoom](https://github.com/d3/d3-interpolate#interpolateZoom) you can disable “smooth” zooming.
