### ISSUE TITLE
Transform jumps when sharing zoom between components

### ISSUE THREAD

**Issue by brewmook** [d3/d3-zoom#55]
I've got two components sharing the same zoom. Depending on which component I use the scroll wheel on, I get different zoom levels because the `__zoom` transform in each component is not kept in sync.

Expected behaviour:
* Zoom in on component A, observe component B also zooming to the same scale.
* Zoom in on component B, observe component A also zooming in further to the same scale as B.

Actual behaviour:
* Zoom in on component A, observe component B also zooming to the same scale.
* Zoom in on component B, components A and B jump back out to the original zoom level before linked zoom commences.

I've worked around the problem by copying `d3.event.transform` into each component's `__zoom` member inside the corresponding component's `zoom` event listener. It doesn't seem right though, I shouldn't be fiddling `__zoom` directly. I don't want to kick off a full `zoom.transform` inside the `zoom` handlers.

Is this how it's supposed to work? Am I expected to do this transform sync myself? If so, what's the _right way_ to do it?

**Comment by mbostock** [comment]
The expected behavior you describe is not the expected behavior. Each element gets its own zoom state (hence d3.zoomTransform) and zooms completely independently. If you want to synchronize zooming, you must apply the zoom transform from the active element to the other elements. If you don’t want to synchronize zooming, you should be careful to only redraw the active element with its zoom transform (and not inadvertently apply this transform to the other elements).
