### ISSUE TITLE
Click + zoom not working properly

### ISSUE THREAD

**Issue by nitaku** [d3/d3-zoom#56]
Clicking the orange circle in [this example](http://bl.ocks.org/nitaku/6545ba8d7146a4843e4bd1b0fa9f1268) should turn it into red, but the callback is not called. In my tests, this is only true when using Chrome on my Microsoft Surface Pro 3 PC. Firefox on the same machine or Chrome on another PC or Mac do not present this behavior. Tapping with fingers also works, the problem arises only when clicking with the mouse.

A [similar example](http://bl.ocks.org/nitaku/c0428b51925dd9d912e638a5d48e5944) that uses d3 version 3 works fine even on my setup.

**Comment by mbostock** [comment]
To confirm: I interpret your report to mean that the problem exists on Chrome + Surface,  and that it works fine on the other platforms you’ve tried. I tested on my Mac with a mouse and the orange circle turned red on click on Chrome, Safari and Firefox which I understand to be the desired behavior.

If it’s not working on Surface, then chances are it’s something to do with pointer emulation. I believe the behavior of browsers very differently with hybrid inputs. (For example, iOS [emulates mouse events](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html) in an attempt to provide compatibility on a device that only natively supports touch. I’m not sure what the Surface does.)

Unfortunately, with no hardware to test on, and with limited resources in general, I’m not willing to investigate a Surface-specific issue. However, if you are able to diagnose and fix the problem yourself, I’d be happy to review a pull request. 

I wonder if the Surface is producing an emulated mousemove event even when the mouse doesn’t move, which would cause `g.moved = true` in [zoom.js](https://github.com/d3/d3-zoom/blob/v1.0.3/src/zoom.js#L249) which would then disable a subsequent click in [dragEnable](https://github.com/d3/d3-drag/blob/v1.0.1/src/nodrag.js#L15). If so, it might be worth changing the logic slightly so that the gesture is only considered *moved* if the mouse moves more than a certain distance, so that the gesture interpretation is more robust.

That said, I’d also consider designing a different interaction, since disambiguating a click from panning is inherently difficult. 😉

**Comment by herrvigg** [comment]
hello,
sorry to spam over all the similar issues but i have to. I don't see how this issue can be closed considering it worked well in v3 and we have no proper solution to make it work in v4.
In my case the problem is not limited to Chrome, i have it on Firefox as well. But even if it were the case a general workaround has to be found! So even though it might be specific to Chrome, i think it might be the same underlying issue so it should be considered in the general case.

This issue looks very similar to the one i opened recently: https://github.com/d3/d3-zoom/issues/66
In my opinion it is also the same issue that was opened here https://github.com/d3/d3-zoom/issues/62
and i just commented it so i will just recopy my comment.

If i reassume, panning on an item part of an element having a zoom behavior makes the click events lost on all items. From this point only the zoom works.

I don't know if this is supposed to be the case with the new zoom in v4, it's not easy to understand what is meant with the prevent default stuff and so on. But what is sure, this used to work in v3 and does not work anymore in v4.

Is this supposed to work like this now? If yes, how can i correctly capture click events on items part of a zoomable container?

NB: the problem exists both on Chrome and Firefox if wondering about it.

https://github.com/d3/d3-zoom/issues/62
