### ISSUE TITLE
d3 responsive zoom behavior on window resizing

### ISSUE THREAD

**Issue by jwmao** [d3/d3-zoom#61]
I am using D3 to set up my chart area that makes use of the zoomable behavior. The chart includes both x and y axis. 

The chart area should be responsive when window is resized. In this case, I need to reset the x and y axis domain and range on window resizing. 

The issue happened with window resizing. I've noticed the zoom focus isn't lined up with the mouse anymore after the following steps:
1) First pan and zoom in the chart area
2) Then resize the window
3) Then pan and zoom the chart area again

After that, the above problem happened. See the following jsfiddle which has this issue. 
http://jsfiddle.net/maow/qLwneqxu/10/

So what's the right way of handing this?

**Comment by mbostock** [comment]
You’ll need to call [*zoom*.transform](https://github.com/d3/d3-zoom/blob/master/README.md#zoom_transform) if you change the domain of the scales in order to keep the zoom’s transform in-sync.

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by jwmao** [comment]
I know this issue has been closed. But I've searched anywhere in d3-js Google Group or stack overflow, I couldn't find the example on how this can be done in d3 version 4. I've posted a question at stack overflow as well. 

http://stackoverflow.com/questions/39735367/d3-zoom-behavior-when-window-is-resized

As you mentioned, if I changed the axis domain on window resize, I need to call zoom.transform. I've tried resetting the translate to the identity transform which seems to fix the mouse jumping problem. But the scale went back to 1, I then I reapply the old scale, then it adds more problems. Is it possible you can post some examples on how this can be done?

**Comment by mbostock** [comment]
You need to set the transform to whatever the new transform should be based on whatever you set the scale’s domains to, not the identity transform. An example is [Brush & Zoom II](http://bl.ocks.org/mbostock/f48fcdb929a620ed97877e4678ab15e6).

**Comment by jwmao** [comment]
So I've checked Brush & Zoom II example. I can see you're resetting the axis domain and then resetting the circles cx and cy based on the modified axis domain in zoom function, but I didn't see where you're doing zoom.transform.

**Comment by mbostock** [comment]
Yes, sorry. That’s the example I meant.

**Comment by jwmao** [comment]
Thanks for you quick response. 

So I've tried your suggestion, call zoom.transform on window resize. What I did is:

1) on window resize, reset the width and height
2) reset the axis domain based on new width, new height and scale
3) then call zoom.transform, something like below:

  svg.call(zoom.transform, d3.zoomIdentity
         .scale(width / (x(currentXDomain[1]) - x(currentXDomain[0])))
         .translate(-x(currentXDomain[0]), -y(currentYDomain[0])));

In my case, if I have reset the axis domain and width, the  .scale(width / (x(currentXDomain[1]) - x(currentXDomain[0]))) will always return 1, and translate value also doesn't seem to be correct. Can you please advise? I created a block, see below:

http://blockbuilder.org/jwmao/b20aa8877c871c860e2598c1e8d1602a

**Comment by mbostock** [comment]
Sorry, but I can’t offer further assistance. Please try the other resources I mentioned previously. Good luck.

**Comment by jwmao** [comment]
ok. Thanks for the help.
