### ISSUE TITLE
zoom is pretty broken when called on node smaller than the <svg /> node

### ISSUE THREAD

**Issue by mrcslws** [d3/d3-zoom#86]
If you apply a zoom to a `<rect />` within an `<svg />`, the behavior can be very strange if the `<rect />` is smaller than the `<svg />`. This happens because d3 uses the parent `<svg />`'s size to determine the zoom extent rather than using the size of the element that it's applied to. [Relevant source](https://github.com/d3/d3-zoom/blob/bfb29610206760e24ad8e3d9abf91715f473abbd/src/zoom.js#L19).

Behaviors I see:

- `translateExtent` is often not properly applied. Through combinations of panning and zooming out, I can cause it to translate way beyond the translateExtent.
- Strange jerkiness.

Here's a gist that demonstrates these issues: https://bl.ocks.org/mrcslws/565393a63d5e017d095686b8fbf5a2f3

Here's the workaround that I'm using.

~~~javascript
function svgRectExtent() {
  var e = this, w, h;

  return [[0, 0],
          [e.width.baseVal.value,
           e.height.baseVal.value]];
}

// On my zoom
var zoom = d3.zoom()
  .extent(svgRectExtent);
~~~

This workaround is just telling it to use the dimensions of the element that it's applying the zoom to, and this makes everything work as expected.

**Comment by mbostock** [comment]
The problem is that you’ve defined a translate (or “world”) extent that is smaller than the zoom (or “viewport”) extent; related #50. It is thus impossible to constrain the view inside the world.

Given the default zoom extent you’re using, which as documented is the bounds of the ancestor SVG element, you’ll want to change the *zoom*.translateExtent to something like:

```js
var zoom = d3.zoom()
    .scaleExtent([1, 40])
    .translateExtent([[0, 0], [+svg.attr("width"), +svg.attr("height")]])
    .on("zoom", zoomed);
```

Alternatively, you could define a compatible *zoom*.extent as follows:

```js
var zoom = d3.zoom()
    .scaleExtent([1, 40])
    .translateExtent([[0, 0], [width, height]])
    .extent([[0, 0], [width, height]])
    .on("zoom", zoomed);
```

I can’t think of a smarter default for *zoom*.extent, since the zoomable content can be modified dynamically; I don’t think using *node*.getBBox would be very predictable, either. So really unless the zoom behavior applies to the entire SVG, you should be specifying the *zoom*.extent explicitly rather than relying on the default.

**Comment by mrcslws** [comment]
@mbostock Thanks for spending time on this. I totally overlooked that `zoom.extent()` was part of the documented API. That's my bad.

I don't think `zoom.extent()` is used in any any of the zoom examples. An example that uses zoom.extent would have helped me. (Context: I was porting [these](http://mrcslws.com/blocks/2016/04/28/life-and-times-of-dendrite-segment.html) to d3 4.0, and getting zooming to work again took a long time.) That's just an FYI -- with d3 you've already done a lot for me!

I'm still seeing some other quirkiness -- I'll file a separate issue: #87
