### ISSUE TITLE
Zoom rect must be positioned with "transform", not with "x"/"y"

### ISSUE THREAD

**Issue by mrcslws** [d3/d3-zoom#87]
If you're applying a `zoom` to a `<rect />` that is positioned within an `<svg />`, you must position the rect with

~~~javascript
rect
  .attr("transform", "translate(42, 42)");
~~~

and not:

~~~javascript
rect
  .attr("x", 42)
  .attr("y", 42);
~~~

Otherwise, the zoom transform is calculated incorrectly. You can see this here: https://bl.ocks.org/mrcslws/387a619d570508451ce2e7209ffaac7d

This caught me off guard. Maybe it's intentional?

**Comment by mbostock** [comment]
This, too, is expected. The element you bind the zoom behavior to determines the coordinate system; this is how the zoom behavior knows the effective coordinate of the mouse, and where you are zooming into.

If you position your rect with *x* and *y* attributes, then what you are showing as ⟨100,100⟩ with the axes is actually ⟨200,200⟩ in the [current coordinate system](https://www.w3.org/TR/SVG/coords.html#EstablishingANewUserSpace) defined by the ancestor SVG element; the RECT element isn’t defining a new coordinate system. You must use a transform to position the rect because it defines a new coordinate system, thus making the effective mouse position align visually with the axes your are using.
