### ISSUE TITLE
Shared d3.event on two elements.

### ISSUE THREAD

**Issue by henev** [d3/d3-zoom#88]
Hi,

I found this nice example of [zooming with minimap](http://codepen.io/billdwhite/pen/QwpYZa), but it is written in the old version v3. I almost convert it to v4 but there is a problem with `d3.event`. In v3 `d3.event` seems to share the zooming params between the two elements where the zoom is called. So if I scale on the main canvas and then on the minimap canvas - the `d3.event` will have the last scale value of the main canvas zoom `d3.event`. But in v4 the both d3 zoom events have somehow separate values for scale or translate. Documentation says:

>The zoom behavior stores the zoom state on the element to which the zoom behavior was applied, not on the zoom behavior itself. This is because the zoom behavior can be applied to many elements simultaneously, and each element can be zoomed independently.

But that leaves the question how I can have one shared zoom event on two elements?

**Comment by mbostock** [comment]
In v4, if you apply a zoom behavior to multiple elements, they will zoom independently because the zoom transform is stored separately on each element, rather than inside the zoom behavior. The current zoom transform can be accessed as *event*.transform within a [zoom event listener](https://github.com/d3/d3-zoom/blob/master/README.md#zoom-events). It can also be accessed for a given *node* (to which you previously applied the zoom behavior) using [d3.zoomTransform](https://github.com/d3/d3-zoom/blob/master/README.md#zoomTransform).

For a minimap, you probably want zooming in the main view to apply [*zoom*.transform](https://github.com/d3/d3-zoom/blob/master/README.md#zoom_transform) to the minimap, and likewise zooming on the minimap to apply [*zoom*.transform](https://github.com/d3/d3-zoom/blob/master/README.md#zoom_transform) to the main view, thereby forcing the two to be in sync. And you’ll either want separate listeners for the main view and the minimap, or to check which element received the zoom event, or to check *event*.sourceEvent, so that when you call *zoom*.transform you don’t start an infinite loop of recursive zoom events.

A closely-related example is [Brush & Zoom](https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172) which uses d3-brush to create a minimap of sorts. However these minimap is controlled via brushing rather than zooming, so you’d need to change the logic a bit. But conceptually it’s very similar; this example uses *event*.sourceEvent to break the infinite loop.

If you have further questions, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by henev** [comment]
Thank you very much @mbostock!

Anyway I succeeded with implementing some of the logic and formulas from your code directly into my zoom handler. It works like a charm. I will post my code just in case someone else is interested and also I will appreciate feedback if I'm doing something very wrong.

So this is the updated zoom handler from v3 to v4:
***Note:** Translation boundery checks not included.*
```javascript
// ....

var scale = 1;
var minScale = .5;
var maxScale = 7.5;
var translation = [0, 0];

// ....

// Used for both main canvas and minimap zoom
var zoom = d3.zoom()
    .on('zoom', zoomHandler);

function zoomHandler(newScale) {
    var prevScale = scale;
    var previousTranslation = getXYFromTranslate(panCanvas.attr('transform'));
    var isZoomEvent = d3.event && d3.event.sourceEvent.deltaY;
    var isDragEvent = d3.event && (d3.event.sourceEvent.movementX || d3.event.sourceEvent.movementY);

    if (isZoomEvent) {
        scale = calculateNewScale(prevScale, d3.event.sourceEvent);
        scale = checkScaleBounderies(scale);

        var mousePosition = d3.mouse(this);

        // Based on d3.js zoom algorythm
        translation[0] = mousePosition[0] - ((mousePosition[0] - previousTranslation[0]) / prevScale) * scale;
        translation[1] = mousePosition[1] - ((mousePosition[1] - previousTranslation[1]) / prevScale) * scale;
    } else if (isDragEvent) {
        translation[0] = previousTranslation[0] + d3.event.sourceEvent.movementX;
        translation[1] = previousTranslation[1] + d3.event.sourceEvent.movementY;
    } else if (newScale) {
        scale = newScale;
    }

    // Apply the new dimensions to the main canvas
    panCanvas.attr('transform', 'translate(' + translation + ') scale(' + scale + ')');

    // Apply the new dimensions to the minimap
    minimap.scale(scale).render();
}

// Calculate the new scale value based on d3.js zoom formula
function calculateNewScale(prevScale, event) {
    return prevScale * Math.pow(2, -event.deltaY * (event.deltaMode ? 120 : 1) / 500);
}

// Check if scale has reached max or min
function checkScaleBounderies(newScale) {
    return Math.max(minScale, Math.min(maxScale, newScale));
}

//....

function getXYFromTranslate(transform) {
    // Create a dummy g for calculation purposes only. This will never
    // be appended to the DOM and will be discarded once this function
    // returns.
    var g = document.createElementNS('http://www.w3.org/2000/svg', 'g');

    // Set the transform attribute to the provided string value.
    g.setAttributeNS(null, 'transform', transform);

    // consolidate the SVGTransformList containing all transformations
    // to a single SVGTransform of type SVG_TRANSFORM_MATRIX and get
    // its SVGMatrix.
    var matrix = g.transform.baseVal.consolidate().matrix;

    // As per definition values e and f are the ones for the translation.
    return [matrix.e, matrix.f];
}
```

**Comment by billdwhite** [comment]
[Here's my post](http://www.billdwhite.com/wordpress/2017/09/12/d3-v4-zooming-understanding-zoombehavior-in-the-pan-and-zoom-minimap/) that discussed how I updated that example to d3 v4

**Comment by rhinojosahdz** [comment]
Kind of a hack but this can quickly be solved if we override the d3.event.transform in all your zoomable elements:

    ...
    minimap.call(zoom);
    mainview.call(zoom);
    ...
    function zoomed() {
      var t = d3.event.transform;
      minimap.node().__zoom = t;
      mainview.node().__zoom = t;
      ...
    }
    ...
