### ISSUE TITLE
Position of first touch is wrong after second touch ends.

### ISSUE THREAD

**Issue by caracal7** [d3/d3-zoom#90]
I have issues then I try to zoom and pan on touch device.
If I rotate fingers while zooming and after release one finger, zoomed group is moving((
I don't have this problem with v3 zoom behaviour... In the d3.v3 everything is going smooth.

for example here and in every my scripts
https://bl.ocks.org/mbostock/2a39a768b1d4bc00a09650edef75ad39

P.S. Sorry for my english...

**Comment by mbostock** [comment]
Confirmed. The code assumes that the first touch (the touch that remains after the second touch ends) is still in the same position as it was when the first touch started, but that’s not the case if there is any rotation, since the zoom behavior only allows panning and zooming and not rotation. We need to update the position of the first touch when the second touch ends.

**Comment by mbostock** [comment]
Fix in 1.1.4.

**Comment by caracal7** [comment]
I understand that this is not related to rotation... I speak too bad for explain))

Thanks, Mike...
